-- MySQL Script generated by MySQL Workbench
-- Tue Jul 28 21:20:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`compteUtilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`compteUtilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`compteUtilisateur` (
  `idcompteUtilisateur` INT NOT NULL,
  `nomUtilisateur` VARCHAR(45) NULL,
  `mdp` VARCHAR(45) NULL,
  `emailPerso` VARCHAR(45) NULL,
  `numéroTelephone` VARCHAR(45) NULL,
  PRIMARY KEY (`idcompteUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`session` ;

CREATE TABLE IF NOT EXISTS `mydb`.`session` (
  `idsession` INT NOT NULL,
  `attribute` VARCHAR(45) NULL,
  `compteUtilisateur_idcompteUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idsession`, `compteUtilisateur_idcompteUtilisateur`),
  CONSTRAINT `fk_session_compteUtilisateur`
    FOREIGN KEY (`compteUtilisateur_idcompteUtilisateur`)
    REFERENCES `mydb`.`compteUtilisateur` (`idcompteUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contact` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contact` (
  `idcontact` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prénom` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `numéroTelephone` VARCHAR(45) NULL,
  `message` VARCHAR(45) NULL,
  `newsletter` VARCHAR(45) NULL,
  `session_idsession` INT NOT NULL,
  `session_compteUtilisateur_idcompteUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idcontact`, `session_idsession`, `session_compteUtilisateur_idcompteUtilisateur`),
  CONSTRAINT `fk_contact_session1`
    FOREIGN KEY (`session_idsession` , `session_compteUtilisateur_idcompteUtilisateur`)
    REFERENCES `mydb`.`session` (`idsession` , `compteUtilisateur_idcompteUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sentinelle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sentinelle` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sentinelle` (
  `idsentinelle` INT NOT NULL,
  PRIMARY KEY (`idsentinelle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.` Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.` Role` ;

CREATE TABLE IF NOT EXISTS `mydb`.` Role` (
  `id Role` INT NOT NULL AUTO_INCREMENT,
  `nomRole` VARCHAR(45) NULL,
  PRIMARY KEY (`id Role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Salarié`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Salarié` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Salarié` (
  `idSalarié` INT NOT NULL AUTO_INCREMENT,
  `emailPro` VARCHAR(45) NULL,
  `site` VARCHAR(45) NULL,
  `droits` VARCHAR(45) NULL,
  `numeroBatiment` VARCHAR(45) NULL,
  `rue` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `codePostal` INT NULL,
  `nom` VARCHAR(45) NULL,
  `prénom` VARCHAR(45) NULL,
  `compteUtilisateur_idcompteUtilisateur` INT NOT NULL,
  ` Role_id Role` INT NOT NULL,
  PRIMARY KEY (`idSalarié`, `compteUtilisateur_idcompteUtilisateur`, ` Role_id Role`),
  CONSTRAINT `fk_Salarié_compteUtilisateur1`
    FOREIGN KEY (`compteUtilisateur_idcompteUtilisateur`)
    REFERENCES `mydb`.`compteUtilisateur` (`idcompteUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Salarié_ Role1`
    FOREIGN KEY (` Role_id Role`)
    REFERENCES `mydb`.` Role` (`id Role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`equipe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`equipe` (
  `idequipe` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `nombreDeMembre` VARCHAR(45) NULL,
  `membres` VARCHAR(45) NULL,
  `Salarié_idSalarié` INT NOT NULL,
  `Salarié_compteUtilisateur_idcompteUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idequipe`, `Salarié_idSalarié`, `Salarié_compteUtilisateur_idcompteUtilisateur`),
  CONSTRAINT `fk_equipe_Salarié1`
    FOREIGN KEY (`Salarié_idSalarié` , `Salarié_compteUtilisateur_idcompteUtilisateur`)
    REFERENCES `mydb`.`Salarié` (`idSalarié` , `compteUtilisateur_idcompteUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`semence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`semence` ;

CREATE TABLE IF NOT EXISTS `mydb`.`semence` (
  `idsemence` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idsemence`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`forme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`forme` ;

CREATE TABLE IF NOT EXISTS `mydb`.`forme` (
  `idforme` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idforme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`variété`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`variété` ;

CREATE TABLE IF NOT EXISTS `mydb`.`variété` (
  `idvariété` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `forme_idforme` INT NOT NULL,
  PRIMARY KEY (`idvariété`),
  CONSTRAINT `fk_variété_forme1`
    FOREIGN KEY (`forme_idforme`)
    REFERENCES `mydb`.`forme` (`idforme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`espèce(Taxinomie)`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`espèce(Taxinomie)` ;

CREATE TABLE IF NOT EXISTS `mydb`.`espèce(Taxinomie)` (
  `idespèce(Taxinomie)` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `variété_idvariété` INT NOT NULL,
  PRIMARY KEY (`idespèce(Taxinomie)`),
  CONSTRAINT `fk_espèce(Taxinomie)_variété1`
    FOREIGN KEY (`variété_idvariété`)
    REFERENCES `mydb`.`variété` (`idvariété`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`série`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`série` ;

CREATE TABLE IF NOT EXISTS `mydb`.`série` (
  `idsérie` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `espèce(Taxinomie)_idespèce(Taxinomie)` INT NOT NULL,
  PRIMARY KEY (`idsérie`),
  CONSTRAINT `fk_série_espèce(Taxinomie)1`
    FOREIGN KEY (`espèce(Taxinomie)_idespèce(Taxinomie)`)
    REFERENCES `mydb`.`espèce(Taxinomie)` (`idespèce(Taxinomie)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`section` ;

CREATE TABLE IF NOT EXISTS `mydb`.`section` (
  `idsection` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `série_idsérie` INT NOT NULL,
  PRIMARY KEY (`idsection`),
  CONSTRAINT `fk_section_série1`
    FOREIGN KEY (`série_idsérie`)
    REFERENCES `mydb`.`série` (`idsérie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  `idgenre` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `section_idsection` INT NOT NULL,
  PRIMARY KEY (`idgenre`),
  CONSTRAINT `fk_genre_section1`
    FOREIGN KEY (`section_idsection`)
    REFERENCES `mydb`.`section` (`idsection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tribu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tribu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tribu` (
  `idtribu` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `genre_idgenre` INT NOT NULL,
  PRIMARY KEY (`idtribu`),
  CONSTRAINT `fk_tribu_genre1`
    FOREIGN KEY (`genre_idgenre`)
    REFERENCES `mydb`.`genre` (`idgenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Famille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Famille` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Famille` (
  `idFamille` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `tribu_idtribu` INT NOT NULL,
  PRIMARY KEY (`idFamille`),
  CONSTRAINT `fk_Famille_tribu1`
    FOREIGN KEY (`tribu_idtribu`)
    REFERENCES `mydb`.`tribu` (`idtribu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ordre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ordre` (
  `idordre` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `Famille_idFamille` INT NOT NULL,
  PRIMARY KEY (`idordre`),
  CONSTRAINT `fk_ordre_Famille1`
    FOREIGN KEY (`Famille_idFamille`)
    REFERENCES `mydb`.`Famille` (`idFamille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`classe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`classe` (
  `idclasse` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `ordre_idordre` INT NOT NULL,
  PRIMARY KEY (`idclasse`),
  CONSTRAINT `fk_classe_ordre1`
    FOREIGN KEY (`ordre_idordre`)
    REFERENCES `mydb`.`ordre` (`idordre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`regne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`regne` ;

CREATE TABLE IF NOT EXISTS `mydb`.`regne` (
  `idregne` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `embranchement` VARCHAR(45) NOT NULL,
  `division` VARCHAR(45) NOT NULL,
  `phylum` VARCHAR(45) NOT NULL,
  `classe_idclasse` INT NOT NULL,
  PRIMARY KEY (`idregne`),
  CONSTRAINT `fk_regne_classe1`
    FOREIGN KEY (`classe_idclasse`)
    REFERENCES `mydb`.`classe` (`idclasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`espece`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`espece` ;

CREATE TABLE IF NOT EXISTS `mydb`.`espece` (
  `idespece` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `semence_idsemence` INT NOT NULL,
  `alerte_idalerte` INT NOT NULL,
  `regne_idregne` INT NOT NULL,
  PRIMARY KEY (`idespece`, `semence_idsemence`, `alerte_idalerte`),
  CONSTRAINT `fk_espece_semence1`
    FOREIGN KEY (`semence_idsemence`)
    REFERENCES `mydb`.`semence` (`idsemence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_espece_regne1`
    FOREIGN KEY (`regne_idregne`)
    REFERENCES `mydb`.`regne` (`idregne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alerte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alerte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alerte` (
  `idalerte` INT NOT NULL AUTO_INCREMENT,
  `urgence` INT NULL,
  `espece_idespece` INT NOT NULL,
  `espece_semence_idsemence` INT NOT NULL,
  `espece_alerte_idalerte` INT NOT NULL,
  PRIMARY KEY (`idalerte`, `espece_idespece`, `espece_semence_idsemence`, `espece_alerte_idalerte`),
  CONSTRAINT `fk_alerte_espece1`
    FOREIGN KEY (`espece_idespece` , `espece_semence_idsemence` , `espece_alerte_idalerte`)
    REFERENCES `mydb`.`espece` (`idespece` , `semence_idsemence` , `alerte_idalerte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`etat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`etat` (
  `idetat` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idetat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`projet` ;

CREATE TABLE IF NOT EXISTS `mydb`.`projet` (
  `idprojet` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `dateDebut` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  `duréeEnMois` VARCHAR(45) NULL,
  `Salarié_idSalarié` INT NOT NULL,
  `Salarié_compteUtilisateur_idcompteUtilisateur` INT NOT NULL,
  `alerte_idalerte` INT NOT NULL,
  `etat_idetat` INT NOT NULL,
  PRIMARY KEY (`idprojet`, `Salarié_idSalarié`, `Salarié_compteUtilisateur_idcompteUtilisateur`, `alerte_idalerte`, `etat_idetat`),
  CONSTRAINT `fk_projet_Salarié1`
    FOREIGN KEY (`Salarié_idSalarié` , `Salarié_compteUtilisateur_idcompteUtilisateur`)
    REFERENCES `mydb`.`Salarié` (`idSalarié` , `compteUtilisateur_idcompteUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projet_alerte1`
    FOREIGN KEY (`alerte_idalerte`)
    REFERENCES `mydb`.`alerte` (`idalerte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projet_etat1`
    FOREIGN KEY (`etat_idetat`)
    REFERENCES `mydb`.`etat` (`idetat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sentinelle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sentinelle` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sentinelle` (
  `idsentinelle` INT NOT NULL AUTO_INCREMENT,
  `Salarié_idSalarié` INT NOT NULL,
  `Salarié_compteUtilisateur_idcompteUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idsentinelle`),
  CONSTRAINT `fk_sentinelle_Salarié1`
    FOREIGN KEY (`Salarié_idSalarié` , `Salarié_compteUtilisateur_idcompteUtilisateur`)
    REFERENCES `mydb`.`Salarié` (`idSalarié` , `compteUtilisateur_idcompteUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LotDeSemence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LotDeSemence` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LotDeSemence` (
  `idLotDeSemence` INT NOT NULL AUTO_INCREMENT,
  `quantiteEnNbDeCaiseses` INT NULL,
  `semence_idsemence` INT NOT NULL,
  PRIMARY KEY (`idLotDeSemence`, `semence_idsemence`),
  CONSTRAINT `fk_LotDeSemence_semence1`
    FOREIGN KEY (`semence_idsemence`)
    REFERENCES `mydb`.`semence` (`idsemence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SiteDeStokage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SiteDeStokage` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SiteDeStokage` (
  `idSiteDeStokage` INT NOT NULL AUTO_INCREMENT,
  `salle` INT NULL,
  `localisation` VARCHAR(45) NULL,
  `LotDeSemence_idLotDeSemence` INT NOT NULL,
  PRIMARY KEY (`idSiteDeStokage`),
  CONSTRAINT `fk_SiteDeStokage_LotDeSemence1`
    FOREIGN KEY (`LotDeSemence_idLotDeSemence`)
    REFERENCES `mydb`.`LotDeSemence` (`idLotDeSemence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SiteDeStokage_has_Salarié`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SiteDeStokage_has_Salarié` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SiteDeStokage_has_Salarié` (
  `SiteDeStokage_idSiteDeStokage` INT NOT NULL,
  `Salarié_idSalarié` INT NOT NULL,
  `Salarié_compteUtilisateur_idcompteUtilisateur` INT NOT NULL,
  PRIMARY KEY (`SiteDeStokage_idSiteDeStokage`, `Salarié_idSalarié`, `Salarié_compteUtilisateur_idcompteUtilisateur`),
  CONSTRAINT `fk_SiteDeStokage_has_Salarié_SiteDeStokage1`
    FOREIGN KEY (`SiteDeStokage_idSiteDeStokage`)
    REFERENCES `mydb`.`SiteDeStokage` (`idSiteDeStokage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SiteDeStokage_has_Salarié_Salarié1`
    FOREIGN KEY (`Salarié_idSalarié` , `Salarié_compteUtilisateur_idcompteUtilisateur`)
    REFERENCES `mydb`.`Salarié` (`idSalarié` , `compteUtilisateur_idcompteUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Droit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Droit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Droit` (
  `idDroit` INT NOT NULL AUTO_INCREMENT,
  `nomDroit` VARCHAR(45) NULL,
  PRIMARY KEY (`idDroit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.` Role_has_Droit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.` Role_has_Droit` ;

CREATE TABLE IF NOT EXISTS `mydb`.` Role_has_Droit` (
  ` Role_id Role` INT NOT NULL,
  `Droit_idDroit` INT NOT NULL,
  PRIMARY KEY (` Role_id Role`, `Droit_idDroit`),
  CONSTRAINT `fk_ Role_has_Droit_ Role1`
    FOREIGN KEY (` Role_id Role`)
    REFERENCES `mydb`.` Role` (`id Role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ Role_has_Droit_Droit1`
    FOREIGN KEY (`Droit_idDroit`)
    REFERENCES `mydb`.`Droit` (`idDroit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Data for table `mydb`.`compteUtilisateur`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`compteUtilisateur` (`idcompteUtilisateur`, `nomUtilisateur`, 
	`mdp`, `emailPerso`, `numéroTelephone`) VALUES (1, 'tony', 'test1234', 'tony@test.fr', '0123456789');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`session`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`session` (`idsession`, `attribute`, `compteUtilisateur_idcompteUtilisateur`) 
	VALUES (1, 'incony', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`contact`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`contact` (`idcontact`, `nom`, `prénom`, `email`,
	`numéroTelephone`, `message`, `newsletter`, `session_idsession`, 
	`session_compteUtilisateur_idcompteUtilisateur`) 
		VALUES (1, 'kozram', 'tony', 'tony@test.fr', '0123456789', 
		'bonjour je vous envois un test', '0', 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.` Role`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.` Role` (`id Role`, `nomRole`) VALUES (NULL, 'stagiaire');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Salarié`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Salarié` (`idSalarié`, `emailPro`, 
`site`, `droits`, `numeroBatiment`, `rue`, `ville`, 
`codePostal`, `nom`, `prénom`, `compteUtilisateur_idcompteUtilisateur`, ` Role_id Role`) 
VALUES (1, 'tonynoe@noe.fr', 'lile', 'inconue', '1', '15', 'villetest', 92123, 
'kozram', 'tony', 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`equipe`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`equipe` (`idequipe`, `nom`, `nombreDeMembre`, `membres`, `Salarié_idSalarié`, 
`Salarié_compteUtilisateur_idcompteUtilisateur`) VALUES (NULL, 'equipe1', '5', '1', 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`semence`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`semence` (`idsemence`) VALUES (NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`forme`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`forme` (`idforme`, `nom`) VALUES (NULL, 'forme1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`variété`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`variété` (`idvariété`, `nom`, `forme_idforme`) VALUES (NULL, 'variété1', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`espèce(Taxinomie)`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`espèce(Taxinomie)` (`idespèce(Taxinomie)`, `nom`, `variété_idvariété`) 
VALUES (NULL, 'espèce1', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`série`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`série` (`idsérie`, `nom`, `espèce(Taxinomie)_idespèce(Taxinomie)`) 
VALUES (NULL, 'série', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`section`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`section` (`idsection`, `nom`, `série_idsérie`) VALUES (NULL, 'section1', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`genre`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`genre` (`idgenre`, `nom`, `section_idsection`) VALUES (NULL, 'genre1', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`tribu`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`tribu` (`idtribu`, `nom`, `genre_idgenre`) VALUES (NULL, 'tribu1', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Famille`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Famille` (`idFamille`, `nom`, `tribu_idtribu`) VALUES (NULL, 'famille1', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ordre`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ordre` (`idordre`, `nom`, `Famille_idFamille`) VALUES (NULL, 'ordre', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`classe`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`classe` (`idclasse`, `nom`, `ordre_idordre`) VALUES (NULL, 'classe1', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`regne`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`regne` (`idregne`, `nom`, `embranchement`, `division`, `phylum`, `classe_idclasse`) 
VALUES (NULL, 'régne1', '1', '1', '1', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`espece`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`espece` (`idespece`, `nom`, `semence_idsemence`, `alerte_idalerte`, `regne_idregne`) 
VALUES (NULL, 'pandaRoux', 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`alerte`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`alerte` (`idalerte`, `urgence`, `espece_idespece`, `espece_semence_idsemence`, 
`espece_alerte_idalerte`) VALUES (NULL, 0, 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`etat`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`etat` (`idetat`, `description`) VALUES (NULL, 'en court');
INSERT INTO `mydb`.`etat` (`idetat`, `description`) VALUES (NULL, 'annuler');
INSERT INTO `mydb`.`etat` (`idetat`, `description`) VALUES (NULL, 'clos');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`projet`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`projet` (`idprojet`, `nom`, `dateDebut`, `status`, `duréeEnMois`, 
`Salarié_idSalarié`, `Salarié_compteUtilisateur_idcompteUtilisateur`, `alerte_idalerte`, `etat_idetat`) 
VALUES (NULL, 'projet1',NULL, 'encour', '6', 1, 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Sentinelle`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Sentinelle` (`idsentinelle`, `Salarié_idSalarié`, 
`Salarié_compteUtilisateur_idcompteUtilisateur`) VALUES (NULL, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`LotDeSemence`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`LotDeSemence` (`idLotDeSemence`, `quantiteEnNbDeCaiseses`, `semence_idsemence`) 
VALUES (NULL, 2, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`SiteDeStokage`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`SiteDeStokage` (`idSiteDeStokage`, `salle`, `localisation`, 
`LotDeSemence_idLotDeSemence`) VALUES (NULL, 1, 'batiment', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Droit`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Droit` (`idDroit`, `nomDroit`) VALUES (NULL, 'consultation');
INSERT INTO `mydb`.`Droit` (`idDroit`, `nomDroit`) VALUES (NULL, 'modification ');
INSERT INTO `mydb`.`Droit` (`idDroit`, `nomDroit`) VALUES (NULL, 'sup');

COMMIT;

alter table `compteutilisateur` add COLUMN nom varchar(20); 
alter table `compteutilisateur` add COLUMN prenom varchar(20) ; 

INSERT INTO `semence` (`idsemence`) VALUES ('2'), ('3');

commit; 