-- MySQL Script generated by MySQL Workbench
-- Tue Jul 14 12:17:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`compteUtilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`compteUtilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`compteUtilisateur` (
  `idcompteUtilisateur` INT NOT NULL,
  `nomUtilisateur` VARCHAR(45) NULL,
  `mdp` VARCHAR(45) NULL,
  `emailPerso` VARCHAR(45) NULL,
  `numéroTelephone` VARCHAR(45) NULL,
  PRIMARY KEY (`idcompteUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`session` ;

CREATE TABLE IF NOT EXISTS `mydb`.`session` (
  `idsession` INT NOT NULL,
  `attribute` VARCHAR(45) NULL,
  `compteUtilisateur_idcompteUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idsession`, `compteUtilisateur_idcompteUtilisateur`),
  CONSTRAINT `fk_session_compteUtilisateur`
    FOREIGN KEY (`compteUtilisateur_idcompteUtilisateur`)
    REFERENCES `mydb`.`compteUtilisateur` (`idcompteUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contact` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contact` (
  `idcontact` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prénom` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `numéroTelephone` VARCHAR(45) NULL,
  `message` VARCHAR(45) NULL,
  `newsletter` VARCHAR(45) NULL,
  `session_idsession` INT NOT NULL,
  `session_compteUtilisateur_idcompteUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idcontact`, `session_idsession`, `session_compteUtilisateur_idcompteUtilisateur`),
  
  CONSTRAINT `fk_contact_session1`
    FOREIGN KEY (`session_idsession` , `session_compteUtilisateur_idcompteUtilisateur`)
    REFERENCES `mydb`.`session` (`idsession` , `compteUtilisateur_idcompteUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sentinelle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sentinelle` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sentinelle` (
  `idsentinelle` INT NOT NULL,
  PRIMARY KEY (`idsentinelle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Salarié`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Salarié` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Salarié` (
  `idSalarié` INT NOT NULL AUTO_INCREMENT,
  `emailPro` VARCHAR(45) NULL,
  `site` VARCHAR(45) NULL,
  `droits` VARCHAR(45) NULL,
  `numeroBatiment` VARCHAR(45) NULL,
  `rue` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `codePostal` INT NULL,
  `nom` VARCHAR(45) NULL,
  `prénom` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `compteUtilisateur_idcompteUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idSalarié`, `compteUtilisateur_idcompteUtilisateur`),
  CONSTRAINT `fk_Salarié_compteUtilisateur1`
    FOREIGN KEY (`compteUtilisateur_idcompteUtilisateur`)
    REFERENCES `mydb`.`compteUtilisateur` (`idcompteUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`equipe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`equipe` (
  `idequipe` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `nombreDeMembre` VARCHAR(45) NULL,
  `membres` VARCHAR(45) NULL,
  `Salarié_idSalarié` INT NOT NULL,
  `Salarié_compteUtilisateur_idcompteUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idequipe`, `Salarié_idSalarié`, `Salarié_compteUtilisateur_idcompteUtilisateur`),
  CONSTRAINT `fk_equipe_Salarié1`
    FOREIGN KEY (`Salarié_idSalarié` , `Salarié_compteUtilisateur_idcompteUtilisateur`)
    REFERENCES `mydb`.`Salarié` (`idSalarié` , `compteUtilisateur_idcompteUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alerte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alerte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alerte` (
  `idalerte` INT NOT NULL AUTO_INCREMENT,
  `urgence` INT NULL,
  PRIMARY KEY (`idalerte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`projet` ;

CREATE TABLE IF NOT EXISTS `mydb`.`projet` (
  `idprojet` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `dateDebut` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  `duréeEnMois` VARCHAR(45) NULL,
  `Salarié_idSalarié` INT NOT NULL,
  `Salarié_compteUtilisateur_idcompteUtilisateur` INT NOT NULL,
  `alerte_idalerte` INT NOT NULL,
  PRIMARY KEY (`idprojet`, `Salarié_idSalarié`, `Salarié_compteUtilisateur_idcompteUtilisateur`, `alerte_idalerte`),
  CONSTRAINT `fk_projet_Salarié1`
    FOREIGN KEY (`Salarié_idSalarié` , `Salarié_compteUtilisateur_idcompteUtilisateur`)
    REFERENCES `mydb`.`Salarié` (`idSalarié` , `compteUtilisateur_idcompteUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projet_alerte1`
    FOREIGN KEY (`alerte_idalerte`)
    REFERENCES `mydb`.`alerte` (`idalerte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sentinelle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sentinelle` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sentinelle` (
  `idsentinelle` INT NOT NULL AUTO_INCREMENT,
  `Salarié_idSalarié` INT NOT NULL,
  `Salarié_compteUtilisateur_idcompteUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idsentinelle`),
  CONSTRAINT `fk_sentinelle_Salarié1`
    FOREIGN KEY (`Salarié_idSalarié` , `Salarié_compteUtilisateur_idcompteUtilisateur`)
    REFERENCES `mydb`.`Salarié` (`idSalarié` , `compteUtilisateur_idcompteUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`semence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`semence` ;

CREATE TABLE IF NOT EXISTS `mydb`.`semence` (
  `idsemence` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idsemence`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LotDeSemence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LotDeSemence` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LotDeSemence` (
  `idLotDeSemence` INT NOT NULL AUTO_INCREMENT,
  `quantiteEnNbDeCaiseses` INT NULL,
  `semence_idsemence` INT NOT NULL,
  PRIMARY KEY (`idLotDeSemence`, `semence_idsemence`),
 CONSTRAINT `fk_LotDeSemence_semence1`
    FOREIGN KEY (`semence_idsemence`)
    REFERENCES `mydb`.`semence` (`idsemence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SiteDeStokage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SiteDeStokage` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SiteDeStokage` (
  `idSiteDeStokage` INT NOT NULL AUTO_INCREMENT,
  `salle` INT NULL,
  `localisation` VARCHAR(45) NULL,
  `LotDeSemence_idLotDeSemence` INT NOT NULL,
  PRIMARY KEY (`idSiteDeStokage`),
  CONSTRAINT `fk_SiteDeStokage_LotDeSemence1`
    FOREIGN KEY (`LotDeSemence_idLotDeSemence`)
    REFERENCES `mydb`.`LotDeSemence` (`idLotDeSemence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SiteDeStokage_has_Salarié`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SiteDeStokage_has_Salarié` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SiteDeStokage_has_Salarié` (
  `SiteDeStokage_idSiteDeStokage` INT NOT NULL,
  `Salarié_idSalarié` INT NOT NULL,
  `Salarié_compteUtilisateur_idcompteUtilisateur` INT NOT NULL,
  PRIMARY KEY (`SiteDeStokage_idSiteDeStokage`, `Salarié_idSalarié`, `Salarié_compteUtilisateur_idcompteUtilisateur`),
 CONSTRAINT `fk_SiteDeStokage_has_Salarié_SiteDeStokage1`
    FOREIGN KEY (`SiteDeStokage_idSiteDeStokage`)
    REFERENCES `mydb`.`SiteDeStokage` (`idSiteDeStokage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SiteDeStokage_has_Salarié_Salarié1`
    FOREIGN KEY (`Salarié_idSalarié` , `Salarié_compteUtilisateur_idcompteUtilisateur`)
    REFERENCES `mydb`.`Salarié` (`idSalarié` , `compteUtilisateur_idcompteUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`espece`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`espece` ;

CREATE TABLE IF NOT EXISTS `mydb`.`espece` (
  `idespece` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `semence_idsemence` INT NOT NULL,
  `alerte_idalerte` INT NOT NULL,
  PRIMARY KEY (`idespece`, `semence_idsemence`, `alerte_idalerte`),
  
  CONSTRAINT `fk_espece_semence1`
    FOREIGN KEY (`semence_idsemence`)
    REFERENCES `mydb`.`semence` (`idsemence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_espece_alerte1`
    FOREIGN KEY (`alerte_idalerte`)
    REFERENCES `mydb`.`alerte` (`idalerte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`embranchement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`embranchement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`embranchement` (
  `idembranchement` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idembranchement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`regne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`regne` ;

CREATE TABLE IF NOT EXISTS `mydb`.`regne` (
  `idregne` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `regnecol` VARCHAR(45) NULL,
  `embranchement_idembranchement` INT NOT NULL,
  PRIMARY KEY (`idregne`, `embranchement_idembranchement`),
  
  CONSTRAINT `fk_regne_embranchement1`
    FOREIGN KEY (`embranchement_idembranchement`)
    REFERENCES `mydb`.`embranchement` (`idembranchement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ordre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ordre` (
  `idordre` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `ordrecol` VARCHAR(45) NULL,
  `regne_idregne` INT NOT NULL,
  `regne_embranchement_idembranchement` INT NOT NULL,
  PRIMARY KEY (`idordre`, `regne_idregne`, `regne_embranchement_idembranchement`),
  
  CONSTRAINT `fk_ordre_regne1`
    FOREIGN KEY (`regne_idregne` , `regne_embranchement_idembranchement`)
    REFERENCES `mydb`.`regne` (`idregne` , `embranchement_idembranchement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`classe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`classe` (
  `idclasse` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `ordre_idordre` INT NOT NULL,
  `ordre_regne_idregne` INT NOT NULL,
  `ordre_regne_embranchement_idembranchement` INT NOT NULL,
  PRIMARY KEY (`idclasse`, `ordre_idordre`, `ordre_regne_idregne`, `ordre_regne_embranchement_idembranchement`),
  
  CONSTRAINT `fk_classe_ordre1`
    FOREIGN KEY (`ordre_idordre` , `ordre_regne_idregne` , `ordre_regne_embranchement_idembranchement`)
    REFERENCES `mydb`.`ordre` (`idordre` , `regne_idregne` , `regne_embranchement_idembranchement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Famille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Famille` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Famille` (
  `idFamille` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `Famillecol` VARCHAR(45) NULL,
  `classe_idclasse` INT NOT NULL,
  `classe_ordre_idordre` INT NOT NULL,
  `classe_ordre_regne_idregne` INT NOT NULL,
  `classe_ordre_regne_embranchement_idembranchement` INT NOT NULL,
  PRIMARY KEY (`idFamille`, `classe_idclasse`, `classe_ordre_idordre`, `classe_ordre_regne_idregne`, `classe_ordre_regne_embranchement_idembranchement`),
  
  CONSTRAINT `fk_Famille_classe1`
    FOREIGN KEY (`classe_idclasse` , `classe_ordre_idordre` , `classe_ordre_regne_idregne` , `classe_ordre_regne_embranchement_idembranchement`)
    REFERENCES `mydb`.`classe` (`idclasse` , `ordre_idordre` , `ordre_regne_idregne` , `ordre_regne_embranchement_idembranchement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`taxinomie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`taxinomie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`taxinomie` (
  `idtaxinomie` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `Famille_idFamille` INT NOT NULL,
  `Famille_classe_idclasse` INT NOT NULL,
  `Famille_classe_ordre_idordre` INT NOT NULL,
  `Famille_classe_ordre_regne_idregne` INT NOT NULL,
  `Famille_classe_ordre_regne_embranchement_idembranchement` INT NOT NULL,
  `espece_idespece` INT NOT NULL,
  `espece_semence_idsemence` INT NOT NULL,
  `espece_alerte_idalerte` INT NOT NULL,
  PRIMARY KEY (`idtaxinomie`, `Famille_idFamille`, `Famille_classe_idclasse`, `Famille_classe_ordre_idordre`, `Famille_classe_ordre_regne_idregne`, `Famille_classe_ordre_regne_embranchement_idembranchement`, `espece_idespece`, `espece_semence_idsemence`, `espece_alerte_idalerte`),
 
 CONSTRAINT `fk_taxinomie_Famille1`
    FOREIGN KEY (`Famille_idFamille` , `Famille_classe_idclasse` , `Famille_classe_ordre_idordre` , `Famille_classe_ordre_regne_idregne` , `Famille_classe_ordre_regne_embranchement_idembranchement`)
    REFERENCES `mydb`.`Famille` (`idFamille` , `classe_idclasse` , `classe_ordre_idordre` , `classe_ordre_regne_idregne` , `classe_ordre_regne_embranchement_idembranchement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_taxinomie_espece1`
    FOREIGN KEY (`espece_idespece` , `espece_semence_idsemence` , `espece_alerte_idalerte`)
    REFERENCES `mydb`.`espece` (`idespece` , `semence_idsemence` , `alerte_idalerte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
